# K-Nearest Neighbors (K-NN)

In [1]:
from abalone import *

In [2]:
dataset = pd.read_csv('abalone.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
# Create a age column from the Rings column + 1.5
dataset['Age'] = dataset['Rings'] + 1.5
dataset.drop('Rings', axis = 1, inplace = True)

In [4]:
# Column transform Sex column
X = column_transformer([0], X)

In [5]:
# Splitting the dataset into the Training set and Test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [6]:
# Feature scale X_train and X_test
X_train, X_test = feature_scale(X_train, X_test)

In [7]:
# Training the K-NN model on the Training set
# Euclidean distance between neighbors of 5
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [8]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[[13 13]
 [ 9  8]
 [ 9 11]
 ...
 [ 7 15]
 [ 9 10]
 [11  9]]


In [9]:
print(confusion_matrix(y_test, y_pred))

[[ 0  6  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  3  5  4  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  9 14  8  6  1  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  4  7 19 23  8  1  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  5 39 23 31 10  6  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  9 32 45 34 13  4  2  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  6 14 39 45 36  8  2  0  0  0  2  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  3 11 16 39 34 20  8  4  1  1  1  1  0  0  0  0  0  0  0  0]
 [ 0  0  0  2  7 17 35 32 20  2  3  0  0  0  2  0  0  1  0  0  0  0  0]
 [ 0  0  0  0  3 12 24 26 15  7  3  0  0  1  0  1  1  0  0  0  0  0  0]
 [ 0  0  0  0  5  4  9  9 13  3  3  0  3  0  2  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  2  7  9  6  1  1  0  0  2  3  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  2  4  4  5  4  1  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  1  2  3  1  1  1  2  1  1  1  1  0  0  0  0  0

In [10]:
accuracy_score(y_test, y_pred)

0.20478468899521532